### ISSUE TITLE
JSONのくくり文字の統一

### ISSUE THREAD

**Issue by ryoichi-obara** [tomoki1207/japanizer-slack#2]
japanizer-for-slack.js 内のJSONのくくり文字を統一しませんか？

個人的にはシングルクォーテーションでもダブルクォーテーションでもどちらでも良いと思います。
http://qiita.com/niusounds/items/f21a28e862a68a098ea7

**Comment by tomoki1207** [comment]
ダブルクォーテーションでないと\nで改行されないと勘違いしてましたが、それはPHPでしたね。
文中に ' は割と出てくると思うので ” で統一しようと思います
